PizzaPortal/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using PizzaPortal.Helpers;
using PizzaPortal.Models;
using System.Data;

namespace PizzaPortal.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;

        public CartController(ApplicationDbContext context)
        {
            _context = context;
        }
        /*[Authorize(Roles = "user")]*/
        public IActionResult Index()
        {
            var cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart.IsNullOrEmpty())
            {
                return RedirectToAction("EmptyCart");
            }
            else
            {
                ViewBag.cart = cart;
                ViewBag.total = cart.Sum(item => item.Pizza.Price * item.Quantity);
                return View();
            }
        }

        public IActionResult Buy(int id)
        {
            if (SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item() { Pizza = _context.Pizzas.SingleOrDefault(p => p.PizzaId == id), Quantity = 1 });
                SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            }

            else
            {
                List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExists(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item() { Pizza = _context.Pizzas.SingleOrDefault(p => p.PizzaId == id), Quantity = 1 });
                }
                SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        public int isExists(int id)
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Pizza.PizzaId == id)
                {
                    return i;
                }
            }
            return -1;
        }

        /*[Authorize(Roles = "user")]*/
        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = isExists(id);
            cart.RemoveAt(index);
            SessionHelper.setObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

       /* [Authorize(Roles = "user")]*/
        public IActionResult Checkout()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Pizza.Price * item.Quantity);
            return View();
        }
        public IActionResult MakePayment()
        {
            return View();
        }
        [HttpPost]

        /*[Authorize(Roles = "user")]*/
        public IActionResult MakePayment(Address addr)
        {
            _context.Addresses.Add(addr);
            _context.SaveChanges();
            ViewBag.address = addr;
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Pizza.Price * item.Quantity);
            return View();
        }

        /*[Authorize(Roles = "user")]*/
        public IActionResult EmptyCart()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart.IsNullOrEmpty())
            {
                return View();
            }
            else
            {
                cart.Clear();
            }
            return View();
        }


        public IActionResult Payment()
        {
            List<Item> cart = SessionHelper.getObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.count = cart.Count();
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Pizza.Price * item.Quantity);
            var addr = _context.Addresses.FirstOrDefault();
            ViewBag.address = addr;
            return View();
        }
    }

}
    

PizzaPortal/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PizzaPortal.Models;
using System.Data;

namespace PizzaPortal.Controllers
{
  
        public class PizzaController : Controller
        {
            private ApplicationDbContext _context;

            public PizzaController(ApplicationDbContext context)
            {
                _context = context;
            }
        
        public IActionResult Index()
            {
                var pizzas = _context.Pizzas.Select(p => new
                {
                    Id = p.PizzaId,
                    Name = p.Name,
                    Price = p.Price,
                    Image = p.Image,
                    Quantity = p.AvailableQuantity,
                    CategoryName = p.Category.Name,
                    Date = p.PizzaAddedDate,
                }).ToList();
                return View(pizzas);
            }
            public IActionResult ViewDetails(int id)
            {
                var pizzas = _context.Pizzas.Where(p => p.PizzaId == id).Select(p => new
                {
                    Id = p.PizzaId,
                    Name = p.Name,
                    Price = p.Price,
                    Image = p.Image,
                    Quantity = p.AvailableQuantity,
                    CategoryName = p.Category.Name,
                    Date = p.PizzaAddedDate,
                }).ToList();
                ViewBag.Result = pizzas;
                return View(pizzas);
            }
        }
    }

PizzaPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PizzaPortal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaPortal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" id="privacy" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                       @if (User.IsInRole("admin"))
                        {
                        @* <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="AdminPage">Admin Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">UserDetails</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ViewProducts">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="DisplayBrands">Brands</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="DisplayCategories">Categories</a>
                            </li>*@
                            
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                <li class="nav-item">
                                    <a class="text-danger nav-link btn btn-outline-info me-2" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            </ul>

                        }
                        else
                                {
                                <li class="nav-item">
                                    <a id="avail-btn" class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Available Products</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">View Cart</a>
                                </li>
                                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                    <li class="nav-item">
                                        <a id="logout-btn" class="text-danger btn btn-outline-info me-2" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                    </li>
                                </ul>
                            }
                        }
                        else
                        {
                            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                                <li class="nav-item" style="float:right;">
                                    <a id="register" class="btn btn-outline-info me-2" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-outline-info me-2" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            </ul>
                        }
                    </ul>
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <footer class="my-5 pt-5 text-body-secondary text-center text-small">
            <hr />
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-body-secondary">Home</a></li>
                  <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Pricing</a></li>
                <li class="nav-item"><a asp-controller="Home" asp-action="Privacy" class="nav-link px-2 text-body-secondary">Privacy</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
            <p class="text-center text-body-secondary">&copy; Pizza Hut</p>
        </footer>
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>